-- ==============================================================================
-- JCI Bangkok Database Migration Reference: Timezone & DateTime Support
-- Date: 2026-10-07
-- Description:
--   Adds support for recording timezones alongside dates with 'Asia/Bangkok'
--   (UTC+7) as the default chapter timezone.
--   Enables dayAndTime picker appearance in Payload CMS admin for optional
--   time recording.
-- ==============================================================================

-- 1. Create Enums for Timezones (Generated by Payload CMS Drizzle ORM)
-- Default value: 'Asia/Bangkok'
--
-- Supported timezones list contains standard IANA names including 'Asia/Bangkok'
-- Example enum names:
--   enum_articles_publishdate_tz
--   enum_events_eventdate_tz
--   enum_events_enddate_tz

-- 2. Articles Table Alterations
-- Adds publishdate_tz column to record timezone with published articles
ALTER TABLE articles
  ADD COLUMN IF NOT EXISTS publishdate_tz enum_articles_publishdate_tz NOT NULL DEFAULT 'Asia/Bangkok';

-- 3. Events Table Alterations
-- Adds eventdate_tz and enddate_tz to record timezone for event start and end
ALTER TABLE events
  ADD COLUMN IF NOT EXISTS eventdate_tz enum_events_eventdate_tz NOT NULL DEFAULT 'Asia/Bangkok';

ALTER TABLE events
  ADD COLUMN IF NOT EXISTS enddate_tz enum_events_enddate_tz DEFAULT 'Asia/Bangkok';

-- ==============================================================================
-- Schema Snapshot for Modified Tables
-- ==============================================================================

-- articles (relevant datetime columns):
--   publish_date   TIMESTAMP WITH TIME ZONE NOT NULL
--   publishdate_tz enum_articles_publishdate_tz NOT NULL DEFAULT 'Asia/Bangkok'

-- events (relevant datetime columns):
--   event_date     TIMESTAMP WITH TIME ZONE NOT NULL
--   eventdate_tz   enum_events_eventdate_tz NOT NULL DEFAULT 'Asia/Bangkok'
--   end_date       TIMESTAMP WITH TIME ZONE
--   enddate_tz     enum_events_enddate_tz DEFAULT 'Asia/Bangkok'
--   event_time     CHARACTER VARYING
