import assert from 'node:assert/strict';
import type { ComponentConfig, Data } from '@puckeditor/core';
import { defineBuilderPlugin } from '../src/lib/builder/plugin-types';
import { createPluginRegistry } from '../src/lib/builder/plugin-registry';
import { migrateBuilderPlugins } from '../src/lib/builder/plugin-migrations';
import { appendBuilderLayout, extractBuilderSection, validateBuilderLayout } from '../src/lib/builder/layout-utils';
import { starterSections } from '../src/lib/builder/starter-sections';
import { readBinding, safeBuilderHref } from '../src/lib/builder/bindings';
import { blockStyleCSS } from '../src/lib/builder/styles';
import { sanitizeBuilderRichText } from '../src/lib/builder/richtext';

const component = { fields: {}, render: () => null } as unknown as ComponentConfig;
const plugin = defineBuilderPlugin({ id: 'test.cards', name: 'Cards', version: '1.0.0', apiVersion: 1, description: 'Test', category: 'Test', components: { TestCard: component } });
assert.throws(() => defineBuilderPlugin({ ...plugin, id: 'Invalid Plugin' }), /Invalid plugin ID/);
assert.throws(() => defineBuilderPlugin({ ...plugin, version: 'latest' }), /Invalid plugin version/);
assert.throws(() => createPluginRegistry({}, [plugin, plugin], [plugin.id]), /Duplicate plugin/);
assert.throws(() => createPluginRegistry({ TestCard: component }, [plugin], [plugin.id]), /already registered/);
assert.throws(() => createPluginRegistry({}, [{ ...plugin, dependencies: ['test.missing'] }], [plugin.id]), /dependency/);
assert.equal(createPluginRegistry({}, [plugin], []).enabled.size, 0);

const original: Data = { root: { props: {} }, content: [] };
let counter = 0;
const first = appendBuilderLayout(original, starterSections[1].layout, () => `test-${++counter}`);
const second = appendBuilderLayout(first, starterSections[1].layout, () => `test-${++counter}`);
validateBuilderLayout(second);
assert.equal(second.content.length, 2);
assert.equal(Object.keys(second.zones || {}).length, 6);
assert.equal(original.content.length, 0);
const section = extractBuilderSection(second, second.content[0].props.id);
assert.equal(section.content.length, 1);
assert.equal(Object.keys(section.zones || {}).length, 3);
assert.deepEqual(section.content[0].props, first.content[0].props);
assert.throws(() => validateBuilderLayout({ ...first, content: [first.content[0], first.content[0]] }), /Duplicate/);
assert.throws(() => appendBuilderLayout(original, { root: { props: {} }, content: [], zones: { 'orphan:content': [] } }), /Orphan/);
assert.throws(() => validateBuilderLayout({ ...original, content: [{ type: 'DynamicCode', props: { id: 'invalid', height: 0, source: { html: '', css: '', javascript: '' } } }] }), /height/);

const migrating = { ...plugin, version: '2.0.0', migrate: (layout: Data) => { layout.content[0].props.title = 'Migrated'; return layout; } };
const before: Data = { root: { props: { pluginVersions: { 'test.cards': '1.0.0' } } } as any, content: [{ type: 'TestCard', props: { id: 'card', title: 'Before' } }] };
const after = migrateBuilderPlugins(before, [migrating], [plugin.id]);
assert.equal(before.content[0].props.title, 'Before');
assert.equal(after.content[0].props.title, 'Migrated');
assert.equal(after.content[0].props.id, 'card');
assert.equal(migrateBuilderPlugins(before, [migrating], []).content[0].props.title, 'Before');
assert.throws(() => migrateBuilderPlugins(after, [plugin], [plugin.id]), /requires v2.0.0/);
assert.throws(() => validateBuilderLayout({ ...original, root: { props: { pluginVersions: { invalid: 'latest' } } } }), /semantic version/);

assert.equal(readBinding({ title: '<strong>Title</strong>', settings: { count: 0 } }, 'title'), '<strong>Title</strong>');
assert.equal(readBinding({ settings: { count: 0 } }, 'settings.count'), '0');
assert.equal(readBinding({}, 'constructor.name'), undefined);
assert.equal(safeBuilderHref('javascript:alert(1)'), '#');
assert.equal(safeBuilderHref('//bad.example'), '#');
assert.equal(safeBuilderHref('/en/events'), '/en/events');
const css = blockStyleCSS('safe-id', { desktop: { padding: 32 }, mobile: { padding: 8, hidden: true }, background: 'red;}body{display:none' });
assert.match(css, /max-width:767px/);
assert.match(css, /padding:8px;display:none/);
assert.doesNotMatch(css, /body|red/);
const sanitized = sanitizeBuilderRichText('<p onclick="bad()">Safe <strong>bold</strong><script>alert(1)</script><a href="javascript:bad()">link</a></p>');
assert.match(sanitized, /<strong>bold<\/strong>/);
assert.doesNotMatch(sanitized, /onclick|script|javascript/);
console.log('Builder checks passed: registry, dependencies, migrations, nested section reuse, bindings, styles, and rich-text safety.');
