/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    events: Event;
    projects: Project;
    articles: Article;
    'board-members': BoardMember;
    members: Member;
    'member-stories': MemberStory;
    partners: Partner;
    forms: Form;
    templates: Template;
    'builder-presets': BuilderPreset;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'board-members': BoardMembersSelect<false> | BoardMembersSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    'member-stories': MemberStoriesSelect<false> | MemberStoriesSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    'builder-presets': BuilderPresetsSelect<false> | BuilderPresetsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'th') | ('en' | 'th')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'builder-settings': BuilderSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'builder-settings': BuilderSettingsSelect<false> | BuilderSettingsSelect<true>;
  };
  locale: 'en' | 'th';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('super-admin' | 'president' | 'secretary' | 'marketing' | 'event-manager' | 'editor' | 'viewer')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Auto-generated from filename if left blank.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Manage every website page, its URL, SEO, publication status and visual layout here. Changing a URL keeps the previous address as a permanent redirect.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Keeps dynamic behavior attached even when the URL changes.
   */
  pageType:
    | 'home'
    | 'about'
    | 'events'
    | 'members'
    | 'membership'
    | 'contact'
    | 'photobomb'
    | 'news'
    | 'projects'
    | 'board'
    | 'custom';
  /**
   * Public URL without the language prefix, for example about-us. Use home for the homepage.
   */
  slug: string;
  legacySlugs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('draft' | 'published') | null;
  /**
   * Visual layout data managed by the Puck Editor.
   */
  puckLayout?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * English and Thai overrides. Empty fields inherit the content defaults shown in the live previews.
   */
  seo?: {
    /**
     * Aim for a clear, concise title. JCI Bangkok is appended automatically; search engines may choose a different title.
     */
    title?: string | null;
    /**
     * Summarize this page for visitors. Length guidance appears above; there is no guaranteed display limit.
     */
    description?: string | null;
    /**
     * Used only for editorial guidance. It does not create a meta keywords tag or affect rankings directly.
     */
    focusKeyphrase?: string | null;
    /**
     * Optional. Inherits the search title.
     */
    socialTitle?: string | null;
    /**
     * Optional. Inherits the search description.
     */
    socialDescription?: string | null;
    /**
     * Choose a sharp landscape image, ideally 1200 × 630. Falls back to the content image, then the site default.
     */
    image?: (number | null) | Media;
    imageAlt?: string | null;
    /**
     * Normally leave empty. Use only when this page intentionally duplicates another URL. Overrides are excluded from the sitemap.
     */
    canonicalUrl?: string | null;
    /**
     * Applies to both languages and removes the page from the sitemap. The page remains public.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
    /**
     * Applies to both languages. This alone does not prevent indexing.
     */
    excludeFromSitemap?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  eventDate: string;
  eventDate_tz: SupportedTimezones;
  /**
   * Enter each time or session on a new line (or rely on time picked in Event Date).
   */
  eventTime?: string | null;
  endDate?: string | null;
  endDate_tz?: SupportedTimezones;
  /**
   * e.g. Free, 500 THB, etc. (Can press Enter for multiple lines)
   */
  price?: string | null;
  venue: string;
  /**
   * Provide an accurate address for event structured data. No address is inferred from the venue name.
   */
  venueAddress?: {
    streetAddress?: string | null;
    addressLocality?: string | null;
    addressRegion?: string | null;
    postalCode?: string | null;
    /**
     * Two-letter country code, for example TH.
     */
    addressCountry?: string | null;
  };
  /**
   * Optional numeric price for search engines. Enter 0 only when registration is truly free. The existing Price field remains the visitor-facing text.
   */
  offerPrice?: number | null;
  offerCurrency?: string | null;
  googleMapsLink?: string | null;
  registrationLink?: string | null;
  facebookPosts?:
    | {
        url: string;
        /**
         * Optional (e.g. Day 1 Photos, Summary, etc.)
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  eventType: 'training' | 'networking' | 'community' | 'general' | 'international' | 'partner';
  hostCommittee?: string | null;
  shortDescription: string;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage: number | Media;
  /**
   * โปสเตอร์รอง (ถ้ามี) เลือกได้หลายรูป จะแสดงอยู่ด้านบนสุด
   */
  secondaryPosters?: (number | Media)[] | null;
  /**
   * แกลเลอรีภาพถ่ายกิจกรรม เลือกทีละหลายๆ รูป และลากจัดลำดับได้ง่าย
   */
  eventPhotos?: (number | Media)[] | null;
  status?: ('draft' | 'upcoming' | 'completed' | 'cancelled') | null;
  featured?: boolean | null;
  /**
   * English and Thai overrides. Empty fields inherit the content defaults shown in the live previews.
   */
  seo?: {
    /**
     * Aim for a clear, concise title. JCI Bangkok is appended automatically; search engines may choose a different title.
     */
    title?: string | null;
    /**
     * Summarize this page for visitors. Length guidance appears above; there is no guaranteed display limit.
     */
    description?: string | null;
    /**
     * Used only for editorial guidance. It does not create a meta keywords tag or affect rankings directly.
     */
    focusKeyphrase?: string | null;
    /**
     * Optional. Inherits the search title.
     */
    socialTitle?: string | null;
    /**
     * Optional. Inherits the search description.
     */
    socialDescription?: string | null;
    /**
     * Choose a sharp landscape image, ideally 1200 × 630. Falls back to the content image, then the site default.
     */
    image?: (number | null) | Media;
    imageAlt?: string | null;
    /**
     * Normally leave empty. Use only when this page intentionally duplicates another URL. Overrides are excluded from the sitemap.
     */
    canonicalUrl?: string | null;
    /**
     * Applies to both languages and removes the page from the sitemap. The page remains public.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
    /**
     * Applies to both languages. This alone does not prevent indexing.
     */
    excludeFromSitemap?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Draft content is visible only to signed-in editors.
   */
  status: 'draft' | 'published';
  title: string;
  slug: string;
  year: number;
  category: 'community' | 'youth' | 'sustainability' | 'entrepreneurship' | 'international';
  problemStatement: string;
  targetBeneficiaries?: string | null;
  activities?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  outcomes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  impactNumbers?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  sdgTags?:
    | (
        | 'sdg-1'
        | 'sdg-2'
        | 'sdg-3'
        | 'sdg-4'
        | 'sdg-5'
        | 'sdg-6'
        | 'sdg-7'
        | 'sdg-8'
        | 'sdg-9'
        | 'sdg-10'
        | 'sdg-11'
        | 'sdg-12'
        | 'sdg-13'
        | 'sdg-14'
        | 'sdg-15'
        | 'sdg-16'
        | 'sdg-17'
      )[]
    | null;
  partners?: string | null;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  reportFile?: (number | null) | Media;
  cta?: string | null;
  /**
   * English and Thai overrides. Empty fields inherit the content defaults shown in the live previews.
   */
  seo?: {
    /**
     * Aim for a clear, concise title. JCI Bangkok is appended automatically; search engines may choose a different title.
     */
    title?: string | null;
    /**
     * Summarize this page for visitors. Length guidance appears above; there is no guaranteed display limit.
     */
    description?: string | null;
    /**
     * Used only for editorial guidance. It does not create a meta keywords tag or affect rankings directly.
     */
    focusKeyphrase?: string | null;
    /**
     * Optional. Inherits the search title.
     */
    socialTitle?: string | null;
    /**
     * Optional. Inherits the search description.
     */
    socialDescription?: string | null;
    /**
     * Choose a sharp landscape image, ideally 1200 × 630. Falls back to the content image, then the site default.
     */
    image?: (number | null) | Media;
    imageAlt?: string | null;
    /**
     * Normally leave empty. Use only when this page intentionally duplicates another URL. Overrides are excluded from the sitemap.
     */
    canonicalUrl?: string | null;
    /**
     * Applies to both languages and removes the page from the sitemap. The page remains public.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
    /**
     * Applies to both languages. This alone does not prevent indexing.
     */
    excludeFromSitemap?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  /**
   * Draft content is visible only to signed-in editors.
   */
  status: 'draft' | 'published';
  title: string;
  slug: string;
  author: number | User;
  /**
   * Approved public byline. Falls back to JCI Bangkok Team; administrative email addresses are never displayed.
   */
  authorDisplayName?: string | null;
  category: 'news' | 'event-recap' | 'member-story' | 'president-message' | 'partner-announcement' | 'knowledge';
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  coverImage: number | Media;
  summary: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishDate: string;
  publishDate_tz: SupportedTimezones;
  relatedEvent?: (number | null) | Event;
  relatedProject?: (number | null) | Project;
  /**
   * English and Thai overrides. Empty fields inherit the content defaults shown in the live previews.
   */
  seo?: {
    /**
     * Aim for a clear, concise title. JCI Bangkok is appended automatically; search engines may choose a different title.
     */
    title?: string | null;
    /**
     * Summarize this page for visitors. Length guidance appears above; there is no guaranteed display limit.
     */
    description?: string | null;
    /**
     * Used only for editorial guidance. It does not create a meta keywords tag or affect rankings directly.
     */
    focusKeyphrase?: string | null;
    /**
     * Optional. Inherits the search title.
     */
    socialTitle?: string | null;
    /**
     * Optional. Inherits the search description.
     */
    socialDescription?: string | null;
    /**
     * Choose a sharp landscape image, ideally 1200 × 630. Falls back to the content image, then the site default.
     */
    image?: (number | null) | Media;
    imageAlt?: string | null;
    /**
     * Normally leave empty. Use only when this page intentionally duplicates another URL. Overrides are excluded from the sitemap.
     */
    canonicalUrl?: string | null;
    /**
     * Applies to both languages and removes the page from the sitemap. The page remains public.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
    /**
     * Applies to both languages. This alone does not prevent indexing.
     */
    excludeFromSitemap?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members".
 */
export interface BoardMember {
  id: number;
  name: string;
  position: string;
  year: number;
  photo: number | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  companyRole?: string | null;
  yearJoined?: number | null;
  linkedin?: string | null;
  displayOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * ข้อมูลสมาชิกทั่วไปที่จะแสดงอยู่ด้านล่างของคณะกรรมการ (Board Members)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name: string;
  photo?: (number | null) | Media;
  /**
   * ตำแหน่งและบริษัท เช่น "CEO, Acme Corp"
   */
  companyRole?: string | null;
  yearJoined?: number | null;
  linkedin?: string | null;
  displayOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-stories".
 */
export interface MemberStory {
  id: number;
  memberName: string;
  yearJoined: number;
  chapterRole?: string | null;
  profession?: string | null;
  storyTitle: string;
  quote: string;
  fullStory?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photo: number | Media;
  relatedProjects?: (number | Project)[] | null;
  relatedEvents?: (number | Event)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  organizationName: string;
  logo: number | Media;
  website?: string | null;
  partnerType: 'sponsor' | 'partner' | 'embassy' | 'university' | 'community';
  partnershipYear: number;
  description?: string | null;
  relatedProjects?: (number | Project)[] | null;
  relatedEvents?: (number | Event)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  inquiryType: 'membership' | 'partnership' | 'media' | 'general';
  message: string;
  consent: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: number;
  title: string;
  /**
   * What part of the site this template controls.
   */
  type:
    | 'header'
    | 'footer'
    | 'event-single'
    | 'news-single'
    | 'project-single'
    | 'member-board-year'
    | 'home'
    | 'events-listing'
    | 'members-listing'
    | 'about'
    | 'contact'
    | 'membership'
    | 'photobomb'
    | 'news-listing'
    | 'projects-listing'
    | 'board-listing'
    | 'archive';
  status?: ('draft' | 'published') | null;
  puckLayout?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Reusable copies of sections or layouts. Insertions are independent copies, not linked global components.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "builder-presets".
 */
export interface BuilderPreset {
  id: number;
  title: string;
  puckLayout:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'board-members';
        value: number | BoardMember;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'member-stories';
        value: number | MemberStory;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'templates';
        value: number | Template;
      } | null)
    | ({
        relationTo: 'builder-presets';
        value: number | BuilderPreset;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  pageType?: T;
  slug?: T;
  legacySlugs?: T;
  status?: T;
  puckLayout?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        focusKeyphrase?: T;
        socialTitle?: T;
        socialDescription?: T;
        image?: T;
        imageAlt?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
        excludeFromSitemap?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  eventDate?: T;
  eventDate_tz?: T;
  eventTime?: T;
  endDate?: T;
  endDate_tz?: T;
  price?: T;
  venue?: T;
  venueAddress?:
    | T
    | {
        streetAddress?: T;
        addressLocality?: T;
        addressRegion?: T;
        postalCode?: T;
        addressCountry?: T;
      };
  offerPrice?: T;
  offerCurrency?: T;
  googleMapsLink?: T;
  registrationLink?: T;
  facebookPosts?:
    | T
    | {
        url?: T;
        label?: T;
        id?: T;
      };
  eventType?: T;
  hostCommittee?: T;
  shortDescription?: T;
  fullDescription?: T;
  coverImage?: T;
  secondaryPosters?: T;
  eventPhotos?: T;
  status?: T;
  featured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        focusKeyphrase?: T;
        socialTitle?: T;
        socialDescription?: T;
        image?: T;
        imageAlt?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
        excludeFromSitemap?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  slug?: T;
  year?: T;
  category?: T;
  problemStatement?: T;
  targetBeneficiaries?: T;
  activities?: T;
  outcomes?: T;
  impactNumbers?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  sdgTags?: T;
  partners?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  reportFile?: T;
  cta?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        focusKeyphrase?: T;
        socialTitle?: T;
        socialDescription?: T;
        image?: T;
        imageAlt?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
        excludeFromSitemap?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  slug?: T;
  author?: T;
  authorDisplayName?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  coverImage?: T;
  summary?: T;
  body?: T;
  publishDate?: T;
  publishDate_tz?: T;
  relatedEvent?: T;
  relatedProject?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        focusKeyphrase?: T;
        socialTitle?: T;
        socialDescription?: T;
        image?: T;
        imageAlt?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
        excludeFromSitemap?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members_select".
 */
export interface BoardMembersSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  year?: T;
  photo?: T;
  bio?: T;
  companyRole?: T;
  yearJoined?: T;
  linkedin?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  photo?: T;
  companyRole?: T;
  yearJoined?: T;
  linkedin?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-stories_select".
 */
export interface MemberStoriesSelect<T extends boolean = true> {
  memberName?: T;
  yearJoined?: T;
  chapterRole?: T;
  profession?: T;
  storyTitle?: T;
  quote?: T;
  fullStory?: T;
  photo?: T;
  relatedProjects?: T;
  relatedEvents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  organizationName?: T;
  logo?: T;
  website?: T;
  partnerType?: T;
  partnershipYear?: T;
  description?: T;
  relatedProjects?: T;
  relatedEvents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  inquiryType?: T;
  message?: T;
  consent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  status?: T;
  puckLayout?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "builder-presets_select".
 */
export interface BuilderPresetsSelect<T extends boolean = true> {
  title?: T;
  puckLayout?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Fallback image for SEO/social cards when content has no image. Recommended 1200 × 630.
   */
  defaultSocialImage?: (number | null) | Media;
  siteName: string;
  logo?: (number | null) | Media;
  mainNav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?: {
    facebook?: string | null;
    linkedin?: string | null;
    instagram?: string | null;
  };
  contactEmail?: string | null;
  footerText?: string | null;
  currentYearTheme?: string | null;
  membershipFormLink?: string | null;
  membershipCoverImage?: (number | null) | Media;
  aboutCoverImage?: (number | null) | Media;
  homeHeroImage?: (number | null) | Media;
  homePathway1?: (number | null) | Media;
  homePathway2?: (number | null) | Media;
  homePathway3?: (number | null) | Media;
  homePathway4?: (number | null) | Media;
  memberStoryFallback?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items: {
    label: string;
    labelTh?: string | null;
    linkType?: ('page' | 'custom') | null;
    /**
     * The link follows this page automatically when its URL changes.
     */
    page?: (number | null) | Page;
    /**
     * Relative URL, anchor, email, phone number or full external URL.
     */
    href?: string | null;
    /**
     * Recommended only for external websites.
     */
    openInNewTab?: boolean | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage installed builder plugins. Changes affect the editor and website; existing block data is retained.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "builder-settings".
 */
export interface BuilderSetting {
  id: number;
  plugins?:
    | {
        /**
         * jci.content: Content Essentials; jci.interactive: Interactive Content; jci.embeds: Video Embeds; jci.code: Dynamic Code
         */
        pluginId: string;
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  defaultSocialImage?: T;
  siteName?: T;
  logo?: T;
  mainNav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        facebook?: T;
        linkedin?: T;
        instagram?: T;
      };
  contactEmail?: T;
  footerText?: T;
  currentYearTheme?: T;
  membershipFormLink?: T;
  membershipCoverImage?: T;
  aboutCoverImage?: T;
  homeHeroImage?: T;
  homePathway1?: T;
  homePathway2?: T;
  homePathway3?: T;
  homePathway4?: T;
  memberStoryFallback?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        labelTh?: T;
        linkType?: T;
        page?: T;
        href?: T;
        openInNewTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "builder-settings_select".
 */
export interface BuilderSettingsSelect<T extends boolean = true> {
  plugins?:
    | T
    | {
        pluginId?: T;
        enabled?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}